### ISSUE TITLE
where to correctly place ssh_config_file for ssh-key file auth

### ISSUE THREAD

**Issue by protonjhow** [ktbyers/nornir_netmiko#28]
I am trying to glue together Nornir (netmiko), Hashcorp Vault and Netbox in a PoC.

So far i have the following working
* I can read from vault and then place an ssh-key in the working directory with the correct 0600 permissions)
* I can use that key to authenticate to a device at a shell in the working directory using the custom ssh config without auth requests
* I can fetch a list of devices in my inventory from NetboxInventory2 (the names match the ssh file objects)

right now i am trying to find the right place to patch the InitNornir constructor to reference this config file. I have tried the `extra` section of netmiko with `ssh_config_file` and the ssh.config_file options as a kwargs to the InitNornir. 

So far, both produce the same result of `paramiko.ssh_exception.SSHException: No authentication methods available`

Where should I be putting this ssh config file option to honour the content?

example ssh config file content
```
Host spine1-nxos
    Hostname 172.29.151.1
    User lab
    IdentityFile id_packetcoders
    IdentitiesOnly yes
```

**Comment by protonjhow** [comment]
Having poked around on Slack (yay for the free trial with the unlimited history!!!) I found an example from Kirk that seems to have worked 
I edited extras to add use_keys: True and a key_file location
```
NORNIR_EXTRAS_CONSTRUCTOR = {
    "ssh_config_file": "~/.ssh/config",
    "use_keys": True,
    "key_file": "",
}

# snip
# ... then in my main 

    # make a copy of the constructor for editing
    nb_constructor = NORNIR_INVENTORY_CONSTRUCTOR.copy()
    # update the constructor with the netbox url from .env
    nb_constructor["options"]["nb_url"] = config["NB_URL"]
    # update the constructor with the netbox token from vault
    nb_constructor["options"]["nb_token"] = nb_token

    # copy the SSH constructor for editing
    ssh_constructor = NORNIR_SSH_CONSTRUCTOR.copy()
    # add the ssh config file to the constructor
    ssh_constructor["ssh"]["config_file"] = "nebula_ssh_config"

    # make a copy of the extras constructor for editing
    extras = NORNIR_EXTRAS_CONSTRUCTOR.copy()
    # add the ssh config file
    extras["ssh_config_file"] = "nebula_ssh_config"
    extras["key_file"] = config["VAULTED_KEY_NAME"]

    # create a nornir object with the constructors
    nr = setup_nornir(nb_constructor, ssh_constructor, extras)
```

which results in the following appearing in the nr.inventory.dict()
```
  'defaults': {
        'data': {},
        'connection_options': {'netmiko': {'extras': {'ssh_config_file': 'nebula_ssh_config', 'use_keys': True, 'key_file': 'id_packetcoders'}, 'hostname': None, 'port': None, 'username': None, 'password': None, 'platform': None}},
```

after which it all works fine. 

Did I miss this in the docs somewhere? I can make a clean full example if you want to include it in the docs somewhere prominent maybe?

**Comment by ktbyers** [comment]
Netmiko only uses SSH config file for a very small set of things and KeyAlgos are not one of those things (generally SSH config use is limited to SSH proxy config setup).

Netmiko uses `ssh_config_file` argument which can be specified in connection_options > extras (as per what you did above).

In order to modify the key exchange, you would need to modify this:

```python
        paramiko_transport = getattr(paramiko, "Transport")
        paramiko_transport._preferred_kex = ( 
            "diffie-hellman-group14-sha1",
            "diffie-hellman-group-exchange-sha1",
            "diffie-hellman-group-exchange-sha256",
            "diffie-hellman-group1-sha1",
        )  
```

And you would need to do this before connection which would mean you would have to tell Netmiko to not automatically connect.

```python
# Add argument to ConnectHandler call
auto_connect=False
```

Then call the `_open()` method.

Let me know if that works.

**Comment by protonjhow** [comment]
Thanks, Kirk.

Whilst I unpick this a little, as a wise elder of the nornir circle, do you have an opinion on the other executors (scrapli, napalm etc) specifically being more effective at handling a more complex ssh_config file (Kex, jumps and the like?)

I am in the middle of a PoC and im looking at all the options, and I started here, since it was well trodden ground. Any feedback on this would be great. 

Meanwhile I will try to implement this in my existing code and come back to you.

**Comment by ktbyers** [comment]
NAPALM will just use Netmiko (for SSH-based drivers) so that will largely be the same as Netmiko. Scrapli might be easier on KEX as you could potentially directly use SSH-config file there. Should be similar to Netmiko for Proxy difficulty (though Scrapli might be easier for complex, multiple bastion host scenarios once again as it likely can use SSH-config file more directly).

Though you are already in the pretty rare bucket if you need to change the KEX (i.e. that is already a <1% case) and double bastion host would also be a rare scenario.

**Comment by ktbyers** [comment]
It doesn't look like there is anything more to do on this...so I am going to close this issue. Just re-open or create a new issue if there is still something outstanding.
