### ISSUE TITLE
dependency issue with netmiko

### ISSUE THREAD

**Issue by Trasmontinho** [ktbyers/nornir_netmiko#32]
HI @ktbyers, 

I've tried to update my netmiko plugin to the v4.0 but I've seen that there's a dependency issue on this package which make it incompatible with netmiko. Is there a further release of this package that will authorize the use of the v4.0 of Netmiko ? 

Thanks, 

Regards, 

Sam

**Comment by ktbyers** [comment]
Yes, nornir_netmiko needs upgraded to work with Netmiko4.0. It still needs to be done.

**Comment by ktbyers** [comment]
@Trasmontinho FYI, `develop` branch now uses Netmiko 4.X. 

I probably need until NAPALM gets updated to Netmiko 4.X (which I have an open pull-request on) before I can release this to pypi.

**Comment by Trasmontinho** [comment]
Thanks @ktbyers !

I'll try this. 

Regards, 

Sam

**Comment by fseesink** [comment]
Any update on this?  Would really love to see this plugin support Netmiko >=4.

> I probably need until NAPALM gets updated to Netmiko 4.X (which I have an open pull-request on) before I can release this to pypi.

And not sure I follow this.  I mean, I don't see NAPALM as a dependency of nornir_netmiko when I run `pipdeptree`:
```
...
nornir-netmiko==0.1.2
  - netmiko [required: >=3.4.0,<4.0.0, installed: 3.4.0]
    - ntc-templates [required: Any, installed: 3.0.0]
      - textfsm [required: >=1.1.0,<2.0.0, installed: 1.1.2]
        - future [required: Any, installed: 0.18.2]
        - six [required: Any, installed: 1.16.0]
    - paramiko [required: >=2.6.0, installed: 2.10.4]
      - bcrypt [required: >=3.1.3, installed: 3.2.2]
        - cffi [required: >=1.1, installed: 1.15.0]
          - pycparser [required: Any, installed: 2.21]
      - cryptography [required: >=2.5, installed: 37.0.2]
        - cffi [required: >=1.12, installed: 1.15.0]
          - pycparser [required: Any, installed: 2.21]
      - pynacl [required: >=1.0.1, installed: 1.5.0]
        - cffi [required: >=1.4.1, installed: 1.15.0]
          - pycparser [required: Any, installed: 2.21]
      - six [required: Any, installed: 1.16.0]
    - pyserial [required: Any, installed: 3.5]
    - scp [required: >=0.13.2, installed: 0.14.4]
      - paramiko [required: Any, installed: 2.10.4]
        - bcrypt [required: >=3.1.3, installed: 3.2.2]
          - cffi [required: >=1.1, installed: 1.15.0]
            - pycparser [required: Any, installed: 2.21]
        - cryptography [required: >=2.5, installed: 37.0.2]
          - cffi [required: >=1.12, installed: 1.15.0]
            - pycparser [required: Any, installed: 2.21]
        - pynacl [required: >=1.0.1, installed: 1.5.0]
          - cffi [required: >=1.4.1, installed: 1.15.0]
            - pycparser [required: Any, installed: 2.21]
        - six [required: Any, installed: 1.16.0]
    - setuptools [required: >=38.4.0, installed: 62.2.0]
    - tenacity [required: Any, installed: 8.0.1]
...
```

And when I check the NAPALM requirements file, they're indicating that they already require netmiko >=4:  https://github.com/napalm-automation/napalm/blob/develop/requirements.txt

As I said, would very much love to see this updated to support Netmiko >4 (4.1.0 is latest as I type this).  We're utilizing both Netmiko and Nornir for an internal Django project, with different parts leveraging each.  But at present we have to pin Netmiko to < 4 due to using Nornir, which in turn uses this plugin.

**Comment by ktbyers** [comment]
Netmiko 4.0.0 fix is in NAPALM `develop` branch, but hasn't been released to pypi. 

I don't want to push an updated `nornir_netmiko` until I can also push an updated `nornir_napalm` (since nornir_napalm uses Netmiko under the hood). And until next NAPALM is released, I can't do this.

Let me ask Mircea when he plans to release the next NAPALM release.

**Comment by ktbyers** [comment]
This is done. nornir_netmiko, nornir_napalm, and napalm are now all released for Netmiko 4.x
