### ISSUE TITLE
IOS platform setting is faster on dell OS9 switches than dell_os9 platform setting?

### ISSUE THREAD

**Issue by ozschmoz** [ktbyers/nornir_netmiko#42]
Hello, I noticed a weird thing regarding running tasks on dell OS9 switches. Setting the platform as "ios" completes the tasks much faster than setting it as the correct "dell_os9".  I ran a simple task to change port status as both ios and os9 setting and ios took me about 1-2 seconds while os9 setting of the same task took about 10 seconds. I was wondering what could be the cause of this (it appears like ssh connection thing).

**Comment by ktbyers** [comment]
@ozschmoz It looks like `dell_os9` (force10) just uses the default `session_preparation()` method in base_connection.py and doesn't have any custom `session_preperation()` method setup.

The default method will go to a bit of lowest common denominator and be slow.

So that should be improved. That would be where I would look first.

**Comment by ozschmoz** [comment]
Alright then. Thank you.
