### ISSUE TITLE
Release Please

### ISSUE THREAD

**Issue by nniehoff** [ktbyers/nornir_netmiko#62]
I ran into a dependency issue with nornir-netmiko and another package fighting about textfsm.  I came over here to find `develop` has a 4m old patch to remove the textfsm dependency, so I tried it, sure enough, no dependency headaches with the version in develop.  I'm here to ask if it's possible to create a patch release 1.0.1 or something with this patch in it.

**Comment by timeforplanb123** [comment]
I can't install latest `nornir_netmiko 1.0.0` + `netmiko 4.3.0` from PyPI due to `textfsm` package dependency.  The latest PyPI `nornir-netmiko 1.0.0` requires `textfsm 1.1.2` while `netmiko 4.3.0` requires `textfsm >= 1.1.3`, and `pip` installer shows the following error: `nornir-netmiko 1.0.0 requires textfsm==1.1.2, but you have textfsm 1.1.3 which is incompatible`.

Since this has been fixed in the #58 and `develop` branch, please add this fix to the new `nornir_netmiko` PyPI release. Thanks a lot in advance!

**Comment by ktbyers** [comment]
@timeforplanb123 You can just pip install textfsm==1.1.3 and ignore the warning (or `git clone` the develop branch here and install from there).

In other words, there are relatively easy workarounds.

**Comment by ktbyers** [comment]
nornir-netmiko 1.0.1 just released.

https://github.com/ktbyers/nornir_netmiko/releases/tag/1.0.1

https://pypi.org/project/nornir-netmiko/1.0.1/
